version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 25
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dotnet:
        patterns:
          - "*"
