//HintName: CustomerMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class CustomerMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Customer source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("contacts", new AttributeValue { L = source.Contacts.Select(x => new AttributeValue { M = ToItem_CustomerContact(x) }).ToList() });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Customer FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var customer = new global::MyNamespace.Customer
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Contacts = item.TryGetValue("contacts", out var contactsAttr) && contactsAttr.L is { } contactsList ? contactsList.Select(av => FromItem_CustomerContact(av.M)).ToList() : [],
        };
        return customer;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_CustomerContact(global::MyNamespace.CustomerContact customercontact) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("name", customercontact.Name, false, true)
            .SetDateTime("verifiedAt", customercontact.VerifiedAt, "yyyy-MM-dd", false, true);

    private static global::MyNamespace.CustomerContact FromItem_CustomerContact(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.CustomerContact
        {
            Name = map.GetString("name", Requiredness.Optional),
            VerifiedAt = map.GetDateTime("verifiedAt", format: "yyyy-MM-dd", Requiredness.Optional),
        };
    }

}
