//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Entity source) =>
        new Dictionary<string, AttributeValue>(1)
            .Set("items", new AttributeValue { L = source.Items.Select(x => new AttributeValue { M = new Dictionary<string, AttributeValue>().SetString("name", x.Name, false, true) }).ToList() });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Entity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var entity = new global::MyNamespace.Entity
        {
            Items = item.TryGetValue("items", out var itemsAttr) && itemsAttr.L is { } itemsList ? itemsList.Select(av => new global::MyNamespace.CustomClass { Name = av.M.GetString("name", Requiredness.Optional), }).ToList() : null,
        };
        return entity;
    }
}
