//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Entity source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetList<System.Guid>("guidList", source.GuidList, "N", false, true, DynamoKind.L)
            .SetMap<System.TimeSpan>("durations", source.Durations, "G", false, true, DynamoKind.M)
            .SetList<MyNamespace.Status>("statuses", source.Statuses, "D", false, true, DynamoKind.L);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Entity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var entity = new global::MyNamespace.Entity();
        if (item.TryGetList<System.Guid>("guidList", out var var0, format: "N", Requiredness.InferFromNullability, DynamoKind.L)) entity.GuidList = var0!;
        if (item.TryGetMap<System.TimeSpan>("durations", out var var1, format: "G", Requiredness.InferFromNullability, DynamoKind.M)) entity.Durations = var1!;
        if (item.TryGetList<MyNamespace.Status>("statuses", out var var2, format: "D", Requiredness.InferFromNullability, DynamoKind.L)) entity.Statuses = new global::System.Collections.Generic.HashSet<global::MyNamespace.Status>(var2!);
        return entity;
    }
}
