//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Entity source) =>
        new Dictionary<string, AttributeValue>(1)
            .Set("items", new AttributeValue { L = source.Items.Select(x => new AttributeValue { M = ToItem_CustomClass(x) }).ToList() });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Entity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var entity = new global::MyNamespace.Entity
        {
            Items = item.TryGetValue("items", out var itemsAttr) && itemsAttr.L is { } itemsList ? itemsList.Select(av => FromItem_CustomClass(av.M)).ToList() : [],
        };
        return entity;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_CustomClass(global::MyNamespace.CustomClass customclass) =>
        new Dictionary<string, AttributeValue>(1)
            .SetString("name", customclass.Name, false, true);

    private static global::MyNamespace.CustomClass FromItem_CustomClass(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.CustomClass
        {
            Name = map.GetString("name", Requiredness.Optional),
        };
    }

}
