//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Entity source) =>
        new Dictionary<string, AttributeValue>(5)
            .SetList<System.Guid>("guidList", source.GuidList, false, true, DynamoKind.L)
            .SetList<System.Guid>("guidArray", source.GuidArray, false, true, DynamoKind.L)
            .SetMap<System.Guid>("guidMap", source.GuidMap, false, true, DynamoKind.M)
            .SetList<System.Guid>("guidSequence", source.GuidSequence, false, true, DynamoKind.L)
            .SetList<System.Guid>("guidSet", source.GuidSet, false, true, DynamoKind.L);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Entity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var entity = new global::MyNamespace.Entity();
        if (item.TryGetList<System.Guid>("guidList", out var var0, Requiredness.InferFromNullability, DynamoKind.L)) entity.GuidList = var0!;
        if (item.TryGetList<System.Guid>("guidArray", out var var1, Requiredness.InferFromNullability, DynamoKind.L)) entity.GuidArray = var1!.ToArray();
        if (item.TryGetMap<System.Guid>("guidMap", out var var2, Requiredness.InferFromNullability, DynamoKind.M)) entity.GuidMap = var2!;
        if (item.TryGetList<System.Guid>("guidSequence", out var var3, Requiredness.InferFromNullability, DynamoKind.L)) entity.GuidSequence = var3!;
        if (item.TryGetList<System.Guid>("guidSet", out var var4, Requiredness.InferFromNullability, DynamoKind.L)) entity.GuidSet = new global::System.Collections.Generic.HashSet<global::System.Guid>(var4!);
        return entity;
    }
}
