//HintName: CatalogMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class CatalogMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Catalog source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("productMap", new AttributeValue { M = source.ProductMap.ToDictionary(kvp => kvp.Key, kvp => new AttributeValue { M = ToItem_OrderItem(kvp.Value) }) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Catalog FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var catalog = new global::MyNamespace.Catalog
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            ProductMap = item.TryGetValue("productMap", out var productmapAttr) && productmapAttr.M is { } productmapMap ? productmapMap.ToDictionary(kvp => kvp.Key, kvp => FromItem_OrderItem(kvp.Value.M)) : [],
        };
        return catalog;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_OrderItem(global::MyNamespace.OrderItem orderitem) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("name", orderitem.Name, false, true)
            .SetDateTime("createdAt", orderitem.CreatedAt, "yyyy-MM-dd", false, true);

    private static global::MyNamespace.OrderItem FromItem_OrderItem(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.OrderItem
        {
            Name = map.GetString("name", Requiredness.Optional),
            CreatedAt = map.GetDateTime("createdAt", format: "yyyy-MM-dd", Requiredness.Optional),
        };
    }

}
