//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", source.Id, false, true)
            .SetString("customerName", source.CustomerName, false, true)
            .SetDecimal("total", source.Total, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order(
            id: item.GetString("id", Requiredness.InferFromNullability)
        )
        {
            CustomerName = item.GetString("customerName", Requiredness.InferFromNullability),
            Total = item.GetDecimal("total", Requiredness.InferFromNullability),
        };
        return order;
    }
}
