//HintName: PointMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class PointMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Point source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetInt("x", source.X, false, true)
            .SetInt("y", source.Y, false, true)
            .SetInt("z", source.Z, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Point FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var point = new global::MyNamespace.Point
        {
            X = item.GetInt("x", Requiredness.InferFromNullability),
            Y = item.GetInt("y", Requiredness.InferFromNullability),
            Z = item.GetInt("z", Requiredness.InferFromNullability),
        };
        return point;
    }
}
