//HintName: ProductMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ProductMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Product source) =>
        new Dictionary<string, AttributeValue>(4)
            .SetString("id", source.Id, false, true)
            .SetString("name", source.Name, false, true)
            .SetDecimal("price", source.Price, false, true)
            .SetInt("quantity", source.Quantity, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Product FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var product = new global::MyNamespace.Product(
            Id: item.GetString("id", Requiredness.InferFromNullability),
            Name: item.GetString("name", Requiredness.InferFromNullability)
        )
        {
            Price = item.GetDecimal("price", Requiredness.InferFromNullability),
            Quantity = item.GetInt("quantity", Requiredness.InferFromNullability),
        };
        return product;
    }
}
