//HintName: EntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class EntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Entity source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", source.Id, false, true)
            .SetString("name", source.Name, false, true)
            .SetInt("count", source.Count, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Entity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var entity = new global::MyNamespace.Entity(
            id: item.GetString("id", Requiredness.InferFromNullability)
        )
        {
            Name = item.GetString("name", Requiredness.InferFromNullability),
            Count = item.GetInt("count", Requiredness.InferFromNullability),
        };
        return entity;
    }
}
