//HintName: ConfigMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ConfigMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Config source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("name", source.Name, false, true)
            .SetInt("value", source.Value, false, true)
            .SetBool("enabled", source.Enabled, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Config FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var config = new global::MyNamespace.Config
        {
            Name = item.GetString("name", Requiredness.InferFromNullability),
            Value = item.GetInt("value", Requiredness.InferFromNullability),
            Enabled = item.GetBool("enabled", Requiredness.InferFromNullability),
        };
        return config;
    }
}
