//HintName: PersonMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class PersonMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Person source) =>
        new Dictionary<string, AttributeValue>(4)
            .SetString("firstName", source.FirstName, false, true)
            .SetString("lastName", source.LastName, false, true)
            .SetInt("age", source.Age, false, true)
            .SetBool("isActive", source.IsActive, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Person FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var person = new global::MyNamespace.Person(
            firstName: item.GetString("firstName", Requiredness.InferFromNullability),
            lastName: item.GetString("lastName", Requiredness.InferFromNullability),
            age: item.GetInt("age", Requiredness.InferFromNullability),
            isActive: item.GetBool("isActive", Requiredness.InferFromNullability)
        );
        return person;
    }
}
