//HintName: ProductMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

internal static partial class ProductMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    internal static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Product source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("name", source.Name, false, true)
            .SetDateOnly("startDate", source.StartDate, "yyyy-MM-dd", false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    internal static partial global::MyNamespace.Product FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var product = new global::MyNamespace.Product
        {
            Name = item.GetString("name", Requiredness.InferFromNullability),
            StartDate = item.GetDateOnly("startDate", format: "yyyy-MM-dd", Requiredness.InferFromNullability),
        };
        return product;
    }
}
