//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

internal static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    internal static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.ExampleEntity source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("string", source.String, false, true)
            .SetString("nullableString", source.NullableString, false, true)
            .Set("person", PersonToAttr(source));

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    internal static partial global::MyNamespace.ExampleEntity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item) =>
        new global::MyNamespace.ExampleEntity
        {
            String = item.GetString("string", Requiredness.InferFromNullability),
            NullableString = item.GetNullableString("nullableString", Requiredness.InferFromNullability),
            Person = PersonFromAttr(item),
        };
}
