//HintName: ProductMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

internal static partial class ProductMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    internal static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Product source) =>
        new Dictionary<string, AttributeValue>(5)
            .SetGuid("id", source.Id, "N", false, true)
            .SetString("name", source.Name, false, true)
            .SetDateTime("createdAt", source.CreatedAt, "yyyy-MM-dd", false, true)
            .SetTimeSpan("duration", source.Duration, "c", false, true)
            .SetEnum<global::MyNamespace.ProductStatus>("status", source.Status, "G", false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    internal static partial global::MyNamespace.Product FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var product = new global::MyNamespace.Product
        {
            Id = item.GetGuid("id", format: "N", Requiredness.InferFromNullability),
            Name = item.GetString("name", Requiredness.InferFromNullability),
            CreatedAt = item.GetDateTime("createdAt", format: "yyyy-MM-dd", Requiredness.InferFromNullability),
            Duration = item.GetTimeSpan("duration", format: "c", Requiredness.InferFromNullability),
            Status = item.GetEnum<global::MyNamespace.ProductStatus>("status", global::MyNamespace.ProductStatus.Active, format: "G", Requiredness.InferFromNullability),
        };
        return product;
    }
}
