//HintName: UserMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class UserMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.User source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("firstName", source.FirstName, false, true)
            .SetString("lastName", source.LastName, false, true)
            .SetString("email", source.Email, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.User FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var user = new global::MyNamespace.User
        {
            FirstName = item.GetString("firstName", Requiredness.InferFromNullability),
            LastName = item.GetString("lastName", Requiredness.InferFromNullability),
            Email = item.GetString("email", Requiredness.InferFromNullability),
        };
        AfterFromItem(item, ref user);
        return user;
    }
}
