//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source)
    {
        var item = new Dictionary<string, AttributeValue>(3);
        BeforeToItem(source, item);
        item.SetString("customerId", source.CustomerId, false, true);
        item.SetString("orderId", source.OrderId, false, true);
        item.SetDecimal("total", source.Total, false, true);
        AfterToItem(source, item);
        return item;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        BeforeFromItem(item);
        var order = new global::MyNamespace.Order
        {
            CustomerId = item.GetString("customerId", Requiredness.InferFromNullability),
            OrderId = item.GetString("orderId", Requiredness.InferFromNullability),
            Total = item.GetDecimal("total", Requiredness.InferFromNullability),
        };
        AfterFromItem(item, ref order);
        return order;
    }
}
