//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

internal static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    internal static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(1)
            .Set("address", new AttributeValue { M = ToItem_Address(source.Address) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    internal static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Address = item.TryGetValue("address", out var addressAttr) && addressAttr.M is { } addressMap ? FromItem_Address(addressMap) : throw new System.InvalidOperationException("Required attribute 'address' not found."),
        };
        return order;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Address(global::MyNamespace.Address address) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("city", address.City, false, true)
            .SetString("line_1", address.Line1, false, true);

    private static global::MyNamespace.Address FromItem_Address(Dictionary<string, AttributeValue> map)
    {
        var address = new global::MyNamespace.Address();
        if (map.TryGetString("city", out var var0, Requiredness.InferFromNullability)) address.City = var0!;
        if (map.TryGetString("line_1", out var var1, Requiredness.InferFromNullability)) address.Line1 = var1!;
        return address;
    }

}
