//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("shippingAddress", new AttributeValue { M = ToItem_Address(source.ShippingAddress) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            ShippingAddress = item.TryGetValue("shippingAddress", out var shippingaddressAttr) && shippingaddressAttr.M is { } shippingaddressMap ? FromItem_Address(shippingaddressMap) : throw new System.InvalidOperationException("Required attribute 'shippingAddress' not found."),
        };
        if (item.TryGetString("id", out var var0, Requiredness.InferFromNullability)) order.Id = var0!;
        return order;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Address(global::MyNamespace.Address address) =>
        new Dictionary<string, AttributeValue>(5)
            .SetString("line1", address.Line1, false, true)
            .SetString("city", address.City, false, true)
            .SetString("country", address.Country, false, true)
            .SetString("postalCode", address.PostalCode, false, true)
            .SetString("state", address.State, false, true);

    private static global::MyNamespace.Address FromItem_Address(Dictionary<string, AttributeValue> map)
    {
        var address = new global::MyNamespace.Address
        {
            Line1 = map.GetString("line1", Requiredness.Required),
            City = map.GetString("city", Requiredness.Required),
            PostalCode = map.GetNullableString("postalCode", Requiredness.InferFromNullability),
            State = map.GetString("state", Requiredness.Required),
        };
        if (map.TryGetString("country", out var var0, Requiredness.InferFromNullability)) address.Country = var0!;
        return address;
    }

}
