//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("items", new AttributeValue { L = source.Items.Select(x => new AttributeValue { M = ToItem_LineItem(x) }).ToList() });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Items = item.TryGetValue("items", out var itemsAttr) && itemsAttr.L is { } itemsList ? itemsList.Select(av => FromItem_LineItem(av.M)).ToList().ToArray() : [],
        };
        return order;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_LineItem(global::MyNamespace.LineItem lineitem)
    {
        return new Dictionary<string, AttributeValue>()
            .SetString("productId", lineitem.ProductId, false, true)
            .SetInt("quantity", lineitem.Quantity, false, true);
    }


    private static global::MyNamespace.LineItem FromItem_LineItem(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.LineItem
        {
            ProductId = map.GetString("productId", Requiredness.Optional),
            Quantity = map.GetInt("quantity", Requiredness.Optional),
        };
    }

}
