//HintName: ProductMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ProductMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Product source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", source.Id, false, true)
            .SetString("name", source.Name, false, true)
            .Set("details", new AttributeValue { M = new Dictionary<string, AttributeValue>().SetDecimal("price", source.Details.Price, false, true).SetInt("stockCount", source.Details.StockCount, false, true).SetDateTime("lastUpdated", source.Details.LastUpdated, "O", false, true).SetBool("isActive", source.Details.IsActive, false, true) });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Product FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var product = new global::MyNamespace.Product
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Name = item.GetString("name", Requiredness.InferFromNullability),
            Details = item.TryGetValue("details", out var detailsAttr) && detailsAttr.M is { } detailsMap ? new global::MyNamespace.ProductDetails { Price = detailsMap.GetDecimal("price", Requiredness.Optional), StockCount = detailsMap.GetInt("stockCount", Requiredness.Optional), LastUpdated = detailsMap.GetDateTime("lastUpdated", format: "O", Requiredness.Optional), IsActive = detailsMap.GetBool("isActive", Requiredness.Optional), } : null,
        };
        return product;
    }
}
