//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("payload", new AttributeValue { M = ToItem_Attachment(source.Payload) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Payload = item.TryGetValue("payload", out var payloadAttr) && payloadAttr.M is { } payloadMap ? FromItem_Attachment(payloadMap) : throw new System.InvalidOperationException("Required attribute 'payload' not found."),
        };
        return order;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Attachment(global::MyNamespace.Attachment attachment) =>
        new Dictionary<string, AttributeValue>(2)
            .SetBinary("checksum", attachment.Checksum, false, true)
            .SetStream("content", attachment.Content, false, true);

    private static global::MyNamespace.Attachment FromItem_Attachment(Dictionary<string, AttributeValue> map)
    {
        var attachment = new global::MyNamespace.Attachment();
        if (map.TryGetBinary("checksum", out var var0, Requiredness.InferFromNullability)) attachment.Checksum = var0!;
        if (map.TryGetStream("content", out var var1, Requiredness.InferFromNullability)) attachment.Content = var1!;
        return attachment;
    }

}
