//HintName: Level1Mapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class Level1Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Level1 source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .SetIfNotNull("level2Data", source.Level2Data, value => new AttributeValue { M = ToItem_Level2(value) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Level1 FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var level1 = new global::MyNamespace.Level1
        {
            Level2Data = item.TryGetValue("level2Data", out var level2dataAttr) && level2dataAttr.M is { } level2dataMap ? FromItem_Level2(level2dataMap) : null,
        };
        if (item.TryGetString("id", out var var0, Requiredness.InferFromNullability)) level1.Id = var0!;
        return level1;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Level2(global::MyNamespace.Level2 level2) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", level2.Id, false, true)
            .SetIfNotNull("level3Data", level2.Level3Data, value => new AttributeValue { M = ToItem_Level3(value) });

    private static global::MyNamespace.Level2 FromItem_Level2(Dictionary<string, AttributeValue> map)
    {
        var level2 = new global::MyNamespace.Level2
        {
            Level3Data = map.TryGetValue("level3Data", out var map_level3dataAttr) && map_level3dataAttr.M is { } map_level3data ? FromItem_Level3(map_level3data) : null,
        };
        if (map.TryGetString("id", out var var0, Requiredness.InferFromNullability)) level2.Id = var0!;
        return level2;
    }


    private static Dictionary<string, AttributeValue> ToItem_Level3(global::MyNamespace.Level3 level3) =>
        new Dictionary<string, AttributeValue>(1)
            .SetString("id", level3.Id, false, true);

    private static global::MyNamespace.Level3 FromItem_Level3(Dictionary<string, AttributeValue> map)
    {
        var level3 = new global::MyNamespace.Level3();
        if (map.TryGetString("id", out var var0, Requiredness.InferFromNullability)) level3.Id = var0!;
        return level3;
    }

}
