//HintName: AddressMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class AddressMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Address source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("line1", source.Line1, false, true)
            .SetString("city", source.City, false, true)
            .SetString("postalCode", source.PostalCode, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Address FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var address = new global::MyNamespace.Address
        {
            Line1 = item.GetString("line1", Requiredness.InferFromNullability),
            City = item.GetString("city", Requiredness.InferFromNullability),
            PostalCode = item.GetString("postalCode", Requiredness.InferFromNullability),
        };
        return address;
    }
}
