//HintName: AccountMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class AccountMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Account source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("accountId", source.AccountId, false, true)
            .Set("profile", new AttributeValue { M = ToItem_UserProfile(source.Profile) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Account FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var account = new global::MyNamespace.Account
        {
            AccountId = item.GetString("accountId", Requiredness.InferFromNullability),
            Profile = item.TryGetValue("profile", out var profileAttr) && profileAttr.M is { } profileMap ? FromItem_UserProfile(profileMap) : throw new System.InvalidOperationException("Required attribute 'profile' not found."),
        };
        return account;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_UserProfile(global::MyNamespace.UserProfile userprofile) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("displayName", userprofile.DisplayName, false, true)
            .SetList<string>("roles", userprofile.Roles, false, true)
            .Set("orders", new AttributeValue { L = userprofile.Orders.Select(x => new AttributeValue { M = ToItem_PurchaseOrder(x) }).ToList() });

    private static global::MyNamespace.UserProfile FromItem_UserProfile(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.UserProfile
        {
            DisplayName = map.GetString("displayName", Requiredness.InferFromNullability),
            Roles = map.GetList<string>("roles", Requiredness.InferFromNullability),
            Orders = map.TryGetValue("orders", out var ordersAttr) && ordersAttr.L is { } ordersList ? ordersList.Select(av => FromItem_PurchaseOrder(av.M)).ToList() : throw new System.InvalidOperationException("Required attribute 'orders' not found."),
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_PurchaseOrder(global::MyNamespace.PurchaseOrder purchaseorder) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("orderId", purchaseorder.OrderId, false, true)
            .SetIfNotNull("destination", purchaseorder.Destination, value => new AttributeValue { M = ToItem_ShippingAddress(value) })
            .Set("lines", new AttributeValue { L = purchaseorder.Lines.Select(x => new AttributeValue { M = ToItem_LineItem(x) }).ToList() });

    private static global::MyNamespace.PurchaseOrder FromItem_PurchaseOrder(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.PurchaseOrder
        {
            OrderId = map.GetString("orderId", Requiredness.InferFromNullability),
            Destination = map.TryGetValue("destination", out var map_destinationAttr) && map_destinationAttr.M is { } map_destination ? FromItem_ShippingAddress(map_destination) : throw new System.InvalidOperationException("Required nested property 'destination' not found in DynamoDB item."),
            Lines = map.TryGetValue("lines", out var linesAttr) && linesAttr.L is { } linesList ? linesList.Select(av => FromItem_LineItem(av.M)).ToList() : throw new System.InvalidOperationException("Required attribute 'lines' not found."),
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_ShippingAddress(global::MyNamespace.ShippingAddress shippingaddress) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("street", shippingaddress.Street, false, true)
            .SetString("city", shippingaddress.City, false, true)
            .SetString("postalCode", shippingaddress.PostalCode, false, true);

    private static Dictionary<string, AttributeValue> ToItem_LineItem(global::MyNamespace.LineItem lineitem) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("sku", lineitem.Sku, false, true)
            .SetInt("qty", lineitem.Qty, false, true)
            .SetDecimal("price", lineitem.Price, false, true);

    private static global::MyNamespace.ShippingAddress FromItem_ShippingAddress(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.ShippingAddress
        {
            Street = map.GetString("street", Requiredness.InferFromNullability),
            City = map.GetString("city", Requiredness.InferFromNullability),
            PostalCode = map.GetString("postalCode", Requiredness.InferFromNullability),
        };
    }


    private static global::MyNamespace.LineItem FromItem_LineItem(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.LineItem
        {
            Sku = map.GetString("sku", Requiredness.InferFromNullability),
            Qty = map.GetInt("qty", Requiredness.InferFromNullability),
            Price = map.GetDecimal("price", Requiredness.InferFromNullability),
        };
    }

}
