//HintName: CatalogMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class CatalogMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Catalog source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("products", source.Products is null ? new AttributeValue { NULL = true } : new AttributeValue { M = source.Products?.ToDictionary(kvp => kvp.Key, kvp => new AttributeValue { M = ToItem_Product(kvp.Value) }) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Catalog FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var catalog = new global::MyNamespace.Catalog
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Products = item.TryGetValue("products", out var productsAttr) && productsAttr.M is { } productsMap ? productsMap.ToDictionary(kvp => kvp.Key, kvp => FromItem_Product(kvp.Value.M)) : null,
        };
        return catalog;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Product(global::MyNamespace.Product product) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("name", product.Name, false, true)
            .SetDecimal("price", product.Price, false, true);

    private static global::MyNamespace.Product FromItem_Product(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Product
        {
            Name = map.GetString("name", Requiredness.Optional),
            Price = map.GetDecimal("price", Requiredness.Optional),
        };
    }

}
