//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("shippingAddress", new AttributeValue { M = new Dictionary<string, AttributeValue>().SetString("addr_line1", source.ShippingAddress.Line1, false, true).SetString("addr_city", source.ShippingAddress.City, false, true).SetString("postalCode", source.ShippingAddress.PostalCode, false, true) });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            ShippingAddress = item.TryGetValue("shippingAddress", out var shippingaddressAttr) && shippingaddressAttr.M is { } shippingaddressMap ? new global::MyNamespace.Address { Line1 = shippingaddressMap.GetString("addr_line1", Requiredness.Optional), City = shippingaddressMap.GetString("addr_city", Requiredness.Optional), PostalCode = shippingaddressMap.GetString("postalCode", Requiredness.Optional), } : null,
        };
        return order;
    }
}
