//HintName: LineItemMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class LineItemMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.LineItem source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("productId", source.ProductId, false, true)
            .SetInt("quantity", source.Quantity, false, true)
            .SetDecimal("price", source.Price, false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.LineItem FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var lineItem = new global::MyNamespace.LineItem
        {
            ProductId = item.GetString("productId", Requiredness.InferFromNullability),
            Quantity = item.GetInt("quantity", Requiredness.InferFromNullability),
            Price = item.GetDecimal("price", Requiredness.InferFromNullability),
        };
        return lineItem;
    }
}
