//HintName: EventLogMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class EventLogMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.EventLog source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("entries", new AttributeValue { L = source.Entries.Select(x => new AttributeValue { M = ToItem_LogEntry(x) }).ToList() });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.EventLog FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var eventLog = new global::MyNamespace.EventLog
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Entries = item.TryGetValue("entries", out var entriesAttr) && entriesAttr.L is { } entriesList ? entriesList.Select(av => FromItem_LogEntry(av.M)).ToList() : [],
        };
        return eventLog;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_LogEntry(global::MyNamespace.LogEntry logentry) =>
        new Dictionary<string, AttributeValue>(4)
            .SetDateTime("timestamp", logentry.Timestamp, "O", false, true)
            .SetString("message", logentry.Message, false, true)
            .SetInt("severity", logentry.Severity, false, true)
            .SetBool("isError", logentry.IsError, false, true);

    private static global::MyNamespace.LogEntry FromItem_LogEntry(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.LogEntry
        {
            Timestamp = map.GetDateTime("timestamp", format: "O", Requiredness.Optional),
            Message = map.GetString("message", Requiredness.Optional),
            Severity = map.GetInt("severity", Requiredness.Optional),
            IsError = map.GetBool("isError", Requiredness.Optional),
        };
    }

}
