//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("customer", new AttributeValue { M = new Dictionary<string, AttributeValue>().SetString("name", source.Customer.Name, false, true).Set("address", source.Customer.Address is null ? new AttributeValue { NULL = true } : new AttributeValue { M = new Dictionary<string, AttributeValue>().SetString("line1", source.Customer.Address.Line1, false, true).SetString("city", source.Customer.Address.City, false, true) }) });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Customer = item.TryGetValue("customer", out var customerAttr) && customerAttr.M is { } customerMap ? new global::MyNamespace.Customer { Name = customerMap.GetString("name", Requiredness.Optional), Address = customerMap.TryGetValue("address", out var customerMap_addressAttr) && customerMap_addressAttr.M is { } customerMap_address ? new global::MyNamespace.Address { Line1 = customerMap_address.GetString("line1", Requiredness.Optional), City = customerMap_address.GetString("city", Requiredness.Optional), } : null, } : null,
        };
        return order;
    }
}
