//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("customer", new AttributeValue { M = ToItem_Customer(source.Customer) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Customer = item.TryGetValue("customer", out var customerAttr) && customerAttr.M is { } customerMap ? FromItem_Customer(customerMap) : null,
        };
        return order;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Customer(global::MyNamespace.Customer customer) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("name", customer.Name, false, true)
            .SetIfNotNull("address", customer.Address, value => new AttributeValue { M = ToItem_Address(value) });

    private static global::MyNamespace.Customer FromItem_Customer(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Customer
        {
            Name = map.GetString("name", Requiredness.Optional),
            Address = map.TryGetValue("address", out var map_addressAttr) && map_addressAttr.M is { } map_address ? FromItem_Address(map_address) : null,
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_Address(global::MyNamespace.Address address) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("line1", address.Line1, false, true)
            .SetString("city", address.City, false, true);

    private static global::MyNamespace.Address FromItem_Address(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Address
        {
            Line1 = map.GetString("line1", Requiredness.Optional),
            City = map.GetString("city", Requiredness.Optional),
        };
    }

}
