//HintName: ProductMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ProductMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Product source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", source.Id, false, true)
            .SetString("name", source.Name, false, true)
            .Set("details", new AttributeValue { M = ToItem_ProductDetails(source.Details) });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Product FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var product = new global::MyNamespace.Product
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Name = item.GetString("name", Requiredness.InferFromNullability),
            Details = item.TryGetValue("details", out var detailsAttr) && detailsAttr.M is { } detailsMap ? FromItem_ProductDetails(detailsMap) : null,
        };
        return product;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_ProductDetails(global::MyNamespace.ProductDetails productdetails) =>
        new Dictionary<string, AttributeValue>(4)
            .SetDecimal("price", productdetails.Price, false, true)
            .SetInt("stockCount", productdetails.StockCount, false, true)
            .SetDateTime("lastUpdated", productdetails.LastUpdated, "O", false, true)
            .SetBool("isActive", productdetails.IsActive, false, true);

    private static global::MyNamespace.ProductDetails FromItem_ProductDetails(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.ProductDetails
        {
            Price = map.GetDecimal("price", Requiredness.Optional),
            StockCount = map.GetInt("stockCount", Requiredness.Optional),
            LastUpdated = map.GetDateTime("lastUpdated", format: "O", Requiredness.Optional),
            IsActive = map.GetBool("isActive", Requiredness.Optional),
        };
    }

}
