//HintName: CatalogMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class CatalogMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Catalog source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("products", source.Products is null ? new AttributeValue { NULL = true } : new AttributeValue { M = source.Products?.ToDictionary(kvp => kvp.Key, kvp => new AttributeValue { M = global::MyNamespace.ProductMapper.ToItem(kvp.Value) }) });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Catalog FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var catalog = new global::MyNamespace.Catalog
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Products = item.TryGetValue("products", out var productsAttr) && productsAttr.M is { } productsMap ? productsMap.ToDictionary(kvp => kvp.Key, kvp => global::MyNamespace.ProductMapper.FromItem(kvp.Value.M)) : null,
        };
        return catalog;
    }
}
