//HintName: UserMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class UserMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.User source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", source.Id, false, true)
            .SetString("name", source.Name, false, true)
            .Set("currentOrder", new AttributeValue { M = ToItem_Order(source.CurrentOrder) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.User FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var user = new global::MyNamespace.User
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Name = item.GetString("name", Requiredness.InferFromNullability),
            CurrentOrder = item.TryGetValue("currentOrder", out var currentorderAttr) && currentorderAttr.M is { } currentorderMap ? FromItem_Order(currentorderMap) : null,
        };
        return user;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Order(global::MyNamespace.Order order) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("orderId", order.OrderId, false, true)
            .SetDecimal("total", order.Total, false, true)
            .Set("items", new AttributeValue { L = order.Items.Select(x => new AttributeValue { M = ToItem_OrderItem(x) }).ToList() });

    private static global::MyNamespace.Order FromItem_Order(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Order
        {
            OrderId = map.GetString("orderId", Requiredness.Optional),
            Total = map.GetDecimal("total", Requiredness.Optional),
            Items = map.TryGetValue("items", out var itemsAttr) && itemsAttr.L is { } itemsList ? itemsList.Select(av => FromItem_OrderItem(av.M)).ToList() : [],
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_OrderItem(global::MyNamespace.OrderItem orderitem) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("productId", orderitem.ProductId, false, true)
            .SetInt("quantity", orderitem.Quantity, false, true)
            .SetDecimal("unitPrice", orderitem.UnitPrice, false, true);

    private static global::MyNamespace.OrderItem FromItem_OrderItem(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.OrderItem
        {
            ProductId = map.GetString("productId", Requiredness.Optional),
            Quantity = map.GetInt("quantity", Requiredness.Optional),
            UnitPrice = map.GetDecimal("unitPrice", Requiredness.Optional),
        };
    }

}
