//HintName: Level1Mapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class Level1Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Level1 source) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", source.Id, false, true)
            .SetString("name", source.Name, false, true)
            .Set("level2Data", source.Level2Data is null ? new AttributeValue { NULL = true } : new AttributeValue { M = ToItem_Level2(source.Level2Data) });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Level1 FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var level1 = new global::MyNamespace.Level1
        {
            Level2Data = item.TryGetValue("level2Data", out var level2dataAttr) && level2dataAttr.M is { } level2dataMap ? FromItem_Level2(level2dataMap) : null,
        };
        if (item.TryGetString("id", out var var0, Requiredness.InferFromNullability)) level1.Id = var0!;
        if (item.TryGetString("name", out var var1, Requiredness.InferFromNullability)) level1.Name = var1!;
        return level1;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Level2(global::MyNamespace.Level2 level2) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", level2.Id, false, true)
            .SetString("description", level2.Description, false, true)
            .Set("level3Data", level2.Level3Data is null ? new AttributeValue { NULL = true } : new AttributeValue { M = ToItem_Level3(level2.Level3Data) });

    private static global::MyNamespace.Level2 FromItem_Level2(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Level2
        {
            Id = map.GetString("id", Requiredness.Optional),
            Description = map.GetString("description", Requiredness.Optional),
            Level3Data = map.TryGetValue("level3Data", out var map_level3dataAttr) && map_level3dataAttr.M is { } map_level3data ? FromItem_Level3(map_level3data) : null,
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_Level3(global::MyNamespace.Level3 level3) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", level3.Id, false, true)
            .SetInt("value", level3.Value, false, true)
            .Set("level4Data", level3.Level4Data is null ? new AttributeValue { NULL = true } : new AttributeValue { M = ToItem_Level4(level3.Level4Data) });

    private static global::MyNamespace.Level3 FromItem_Level3(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Level3
        {
            Id = map.GetString("id", Requiredness.Optional),
            Value = map.GetInt("value", Requiredness.Optional),
            Level4Data = map.TryGetValue("level4Data", out var map_level4dataAttr) && map_level4dataAttr.M is { } map_level4data ? FromItem_Level4(map_level4data) : null,
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_Level4(global::MyNamespace.Level4 level4) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("id", level4.Id, false, true)
            .SetBool("isActive", level4.IsActive, false, true)
            .SetDecimal("price", level4.Price, false, true);

    private static global::MyNamespace.Level4 FromItem_Level4(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Level4
        {
            Id = map.GetString("id", Requiredness.Optional),
            IsActive = map.GetBool("isActive", Requiredness.Optional),
            Price = map.GetDecimal("price", Requiredness.Optional),
        };
    }

}
