//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("billingAddress", source.BillingAddress is null ? new AttributeValue { NULL = true } : new AttributeValue { M = ToItem_Address(source.BillingAddress) });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            BillingAddress = item.TryGetValue("billingAddress", out var billingaddressAttr) && billingaddressAttr.M is { } billingaddressMap ? FromItem_Address(billingaddressMap) : null,
        };
        return order;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Address(global::MyNamespace.Address address)
    {
        return new Dictionary<string, AttributeValue>()
            .SetString("line1", address.Line1, false, true)
            .SetString("city", address.City, false, true);
    }


    private static global::MyNamespace.Address FromItem_Address(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Address
        {
            Line1 = map.GetString("line1", Requiredness.Optional),
            City = map.GetString("city", Requiredness.Optional),
        };
    }

}
