//HintName: OrgMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrgMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Org source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("orgId", source.OrgId, false, true)
            .Set("division", new AttributeValue { M = ToItem_Division(source.Division) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Org FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var org = new global::MyNamespace.Org
        {
            OrgId = item.GetString("orgId", Requiredness.InferFromNullability),
            Division = item.TryGetValue("division", out var divisionAttr) && divisionAttr.M is { } divisionMap ? FromItem_Division(divisionMap) : null,
        };
        return org;
    }

    // Helper methods for nested object mapping

    private static Dictionary<string, AttributeValue> ToItem_Division(global::MyNamespace.Division division) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("name", division.Name, false, true)
            .Set("departments", new AttributeValue { L = division.Departments.Select(x => new AttributeValue { M = ToItem_Department(x) }).ToList() });

    private static global::MyNamespace.Division FromItem_Division(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Division
        {
            Name = map.GetString("name", Requiredness.Optional),
            Departments = map.TryGetValue("departments", out var departmentsAttr) && departmentsAttr.L is { } departmentsList ? departmentsList.Select(av => FromItem_Department(av.M)).ToList() : [],
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_Department(global::MyNamespace.Department department) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("code", department.Code, false, true)
            .SetIfNotNull("headManager", department.HeadManager, value => new AttributeValue { M = ToItem_Manager(value) })
            .Set("employees", new AttributeValue { L = department.Employees.Select(x => new AttributeValue { M = ToItem_Employee(x) }).ToList() });

    private static global::MyNamespace.Department FromItem_Department(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Department
        {
            Code = map.GetString("code", Requiredness.Optional),
            HeadManager = map.TryGetValue("headManager", out var map_headmanagerAttr) && map_headmanagerAttr.M is { } map_headmanager ? FromItem_Manager(map_headmanager) : null,
            Employees = map.TryGetValue("employees", out var employeesAttr) && employeesAttr.L is { } employeesList ? employeesList.Select(av => FromItem_Employee(av.M)).ToList() : [],
        };
    }


    private static Dictionary<string, AttributeValue> ToItem_Manager(global::MyNamespace.Manager manager) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("fullName", manager.FullName, false, true)
            .SetString("email", manager.Email, false, true);

    private static Dictionary<string, AttributeValue> ToItem_Employee(global::MyNamespace.Employee employee) =>
        new Dictionary<string, AttributeValue>(3)
            .SetString("employeeId", employee.EmployeeId, false, true)
            .SetString("name", employee.Name, false, true)
            .SetList<string>("tags", employee.Tags, false, true);

    private static global::MyNamespace.Manager FromItem_Manager(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Manager
        {
            FullName = map.GetString("fullName", Requiredness.Optional),
            Email = map.GetString("email", Requiredness.Optional),
        };
    }


    private static global::MyNamespace.Employee FromItem_Employee(Dictionary<string, AttributeValue> map)
    {
        return new global::MyNamespace.Employee
        {
            EmployeeId = map.GetString("employeeId", Requiredness.Optional),
            Name = map.GetString("name", Requiredness.Optional),
            Tags = map.GetList<string>("tags", Requiredness.Optional),
        };
    }

}
