//HintName: EventLogMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class EventLogMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.EventLog source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .Set("entries", new AttributeValue { L = source.Entries.Select(x => new AttributeValue { M = new Dictionary<string, AttributeValue>().SetDateTime("timestamp", x.Timestamp, "O", false, true).SetString("message", x.Message, false, true).SetInt("severity", x.Severity, false, true).SetBool("isError", x.IsError, false, true) }).ToList() });

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.EventLog FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var eventLog = new global::MyNamespace.EventLog
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            Entries = item.TryGetValue("entries", out var entriesAttr) && entriesAttr.L is { } entriesList ? entriesList.Select(av => new global::MyNamespace.LogEntry { Timestamp = av.M.GetDateTime("timestamp", format: "O", Requiredness.Optional), Message = av.M.GetString("message", Requiredness.Optional), Severity = av.M.GetInt("severity", Requiredness.Optional), IsError = av.M.GetBool("isError", Requiredness.Optional), }).ToList() : [],
        };
        return eventLog;
    }
}
