//HintName: OrderMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using LayeredCraft.DynamoMapper.Runtime;
using System.Collections.Generic;
using System.Linq;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class OrderMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.Order source) =>
        new Dictionary<string, AttributeValue>(2)
            .SetString("id", source.Id, false, true)
            .SetIfNotNull("billingAddress", source.BillingAddress, value => new AttributeValue { M = global::MyNamespace.AddressMapper.ToItem(value) });

    [global::System.CodeDom.Compiler.GeneratedCode("LayeredCraft.DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.Order FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
    {
        var order = new global::MyNamespace.Order
        {
            Id = item.GetString("id", Requiredness.InferFromNullability),
            BillingAddress = item.TryGetValue("billingAddress", out var billingaddressAttr) && billingaddressAttr.M is { } billingaddressMap ? global::MyNamespace.AddressMapper.FromItem(billingaddressMap) : null,
        };
        return order;
    }
}
