//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.ExampleEntity source)
    {
        var item = new Dictionary<string, AttributeValue>(22);
        item.SetBool("bool", source.Bool);
        item.SetNullableBool("nullable_bool", source.NullableBool);
        item.SetDateTime("date_time", source.DateTime, "I");
        item.SetNullableDateTime("nullable_date_time", source.NullableDateTime, "I");
        item.SetDateTimeOffset("date_time_offset", source.DateTimeOffset, "I");
        item.SetNullableDateTimeOffset("nullable_date_time_offset", source.NullableDateTimeOffset, "I");
        item.SetDecimal("decimal", source.Decimal);
        item.SetNullableDecimal("nullable_decimal", source.NullableDecimal);
        item.SetDouble("double", source.Double);
        item.SetNullableDouble("nullable_double", source.NullableDouble);
        item.SetGuid("guid", source.Guid);
        item.SetNullableGuid("nullable_guid", source.NullableGuid);
        item.SetInt("int", source.Int);
        item.SetNullableInt("nullable_int", source.NullableInt);
        item.SetLong("long", source.Long);
        item.SetNullableLong("nullable_long", source.NullableLong);
        item.SetString("string", source.String);
        item.SetNullableString("nullable_string", source.NullableString);
        item.SetTimeSpan("time_span", source.TimeSpan);
        item.SetNullableTimeSpan("nullable_time_span", source.NullableTimeSpan);
        item.SetEnum("enum", source.Enum);
        item.SetNullableEnum("nullable_enum", source.NullableEnum);
        return item;
    }
    
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.ExampleEntity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
        => new global::MyNamespace.ExampleEntity
        {
            Bool = item.GetBool("bool"),
            NullableBool = item.GetNullableBool("nullable_bool"),
            DateTime = item.GetDateTime("date_time", "I"),
            NullableDateTime = item.GetNullableDateTime("nullable_date_time", "I"),
            DateTimeOffset = item.GetDateTimeOffset("date_time_offset", "I"),
            NullableDateTimeOffset = item.GetNullableDateTimeOffset("nullable_date_time_offset", "I"),
            Decimal = item.GetDecimal("decimal"),
            NullableDecimal = item.GetNullableDecimal("nullable_decimal"),
            Double = item.GetDouble("double"),
            NullableDouble = item.GetNullableDouble("nullable_double"),
            Guid = item.GetGuid("guid"),
            NullableGuid = item.GetNullableGuid("nullable_guid"),
            Int = item.GetInt("int"),
            NullableInt = item.GetNullableInt("nullable_int"),
            Long = item.GetLong("long"),
            NullableLong = item.GetNullableLong("nullable_long"),
            String = item.GetString("string"),
            NullableString = item.GetNullableString("nullable_string"),
            TimeSpan = item.GetTimeSpan("time_span"),
            NullableTimeSpan = item.GetNullableTimeSpan("nullable_time_span"),
            Enum = item.GetEnum("enum", global::MyNamespace.OrderStatus.Pending),
            NullableEnum = item.GetNullableEnum("nullable_enum", global::MyNamespace.OrderStatus.Pending),
        };
}
