//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.ExampleEntity source)
    {
        var item = new Dictionary<string, AttributeValue>(22);
        item.SetBool("bool", source.Bool);
        item.SetNullableBool("nullableBool", source.NullableBool);
        item.SetDateTime("dateTime", source.DateTime, "O");
        item.SetNullableDateTime("nullableDateTime", source.NullableDateTime, "O");
        item.SetDateTimeOffset("dateTimeOffset", source.DateTimeOffset, "O");
        item.SetNullableDateTimeOffset("nullableDateTimeOffset", source.NullableDateTimeOffset, "O");
        item.SetDecimal("decimal", source.Decimal);
        item.SetNullableDecimal("nullableDecimal", source.NullableDecimal);
        item.SetDouble("double", source.Double);
        item.SetNullableDouble("nullableDouble", source.NullableDouble);
        item.SetGuid("guid", source.Guid);
        item.SetNullableGuid("nullableGuid", source.NullableGuid);
        item.SetInt("int", source.Int);
        item.SetNullableInt("nullableInt", source.NullableInt);
        item.SetLong("long", source.Long);
        item.SetNullableLong("nullableLong", source.NullableLong);
        item.SetString("string", source.String);
        item.SetNullableString("nullableString", source.NullableString);
        item.SetTimeSpan("timeSpan", source.TimeSpan);
        item.SetNullableTimeSpan("nullableTimeSpan", source.NullableTimeSpan);
        item.SetEnum("enum", source.Enum);
        item.SetNullableEnum("nullableEnum", source.NullableEnum);
        return item;
    }
    
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.ExampleEntity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
        => new global::MyNamespace.ExampleEntity
        {
            Bool = item.GetBool("bool"),
            NullableBool = item.GetNullableBool("nullableBool"),
            DateTime = item.GetDateTime("dateTime", "O"),
            NullableDateTime = item.GetNullableDateTime("nullableDateTime", "O"),
            DateTimeOffset = item.GetDateTimeOffset("dateTimeOffset", "O"),
            NullableDateTimeOffset = item.GetNullableDateTimeOffset("nullableDateTimeOffset", "O"),
            Decimal = item.GetDecimal("decimal"),
            NullableDecimal = item.GetNullableDecimal("nullableDecimal"),
            Double = item.GetDouble("double"),
            NullableDouble = item.GetNullableDouble("nullableDouble"),
            Guid = item.GetGuid("guid"),
            NullableGuid = item.GetNullableGuid("nullableGuid"),
            Int = item.GetInt("int"),
            NullableInt = item.GetNullableInt("nullableInt"),
            Long = item.GetLong("long"),
            NullableLong = item.GetNullableLong("nullableLong"),
            String = item.GetString("string"),
            NullableString = item.GetNullableString("nullableString"),
            TimeSpan = item.GetTimeSpan("timeSpan"),
            NullableTimeSpan = item.GetNullableTimeSpan("nullableTimeSpan"),
            Enum = item.GetEnum("enum", global::MyNamespace.OrderStatus.Pending),
            NullableEnum = item.GetNullableEnum("nullableEnum", global::MyNamespace.OrderStatus.Pending),
        };
}
