//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.ExampleEntity source)
        => new Dictionary<string, AttributeValue>(22)
        {
            { "bool", source.Bool.ToAttributeValue() },
            { "nullable_bool", source.NullableBool.ToNullableAttributeValue() },
            { "date_time", source.DateTime.ToAttributeValue("I") },
            { "nullable_date_time", source.NullableDateTime.ToNullableAttributeValue("I") },
            { "date_time_offset", source.DateTimeOffset.ToAttributeValue("I") },
            { "nullable_date_time_offset", source.NullableDateTimeOffset.ToNullableAttributeValue("I") },
            { "decimal", source.Decimal.ToAttributeValue() },
            { "nullable_decimal", source.NullableDecimal.ToNullableAttributeValue() },
            { "double", source.Double.ToAttributeValue() },
            { "nullable_double", source.NullableDouble.ToNullableAttributeValue() },
            { "guid", source.Guid.ToAttributeValue() },
            { "nullable_guid", source.NullableGuid.ToNullableAttributeValue() },
            { "int", source.Int.ToAttributeValue() },
            { "nullable_int", source.NullableInt.ToNullableAttributeValue() },
            { "long", source.Long.ToAttributeValue() },
            { "nullable_long", source.NullableLong.ToNullableAttributeValue() },
            { "string", source.String.ToAttributeValue() },
            { "nullable_string", source.NullableString.ToNullableAttributeValue() },
            { "time_span", source.TimeSpan.ToAttributeValue() },
            { "nullable_time_span", source.NullableTimeSpan.ToNullableAttributeValue() },
            { "enum", source.Enum.ToAttributeValue() },
            { "nullable_enum", source.NullableEnum.ToNullableAttributeValue() },
        };
    
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.ExampleEntity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
        => new global::MyNamespace.ExampleEntity
        {
            Bool = item.GetBool("bool"),
            NullableBool = item.GetNullableBool("nullable_bool"),
            DateTime = item.GetDateTimeExact("date_time", "I"),
            NullableDateTime = item.GetNullableDateTimeExact("nullable_date_time", "I"),
            DateTimeOffset = item.GetDateTimeOffsetExact("date_time_offset", "I"),
            NullableDateTimeOffset = item.GetNullableDateTimeOffsetExact("nullable_date_time_offset", "I"),
            Decimal = item.GetDecimal("decimal"),
            NullableDecimal = item.GetNullableDecimal("nullable_decimal"),
            Double = item.GetDouble("double"),
            NullableDouble = item.GetNullableDouble("nullable_double"),
            Guid = item.GetGuid("guid"),
            NullableGuid = item.GetNullableGuid("nullable_guid"),
            Int = item.GetInt("int"),
            NullableInt = item.GetNullableInt("nullable_int"),
            Long = item.GetLong("long"),
            NullableLong = item.GetNullableLong("nullable_long"),
            String = item.GetString("string"),
            NullableString = item.GetNullableString("nullable_string"),
            TimeSpan = item.GetTimeSpan("time_span"),
            NullableTimeSpan = item.GetNullableTimeSpan("nullable_time_span"),
            Enum = item.GetEnum("enum", global::MyNamespace.OrderStatus.Pending),
            NullableEnum = item.GetNullableEnum<global::MyNamespace.OrderStatus>("nullable_enum"),
        };
}
