//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.ExampleEntity source) =>
        new Dictionary<string, AttributeValue>(22)
            .SetBool("bool", source.Bool, false, true)
            .SetBool("nullableBool", source.NullableBool, false, true)
            .SetDateTime("dateTime", source.DateTime, format: "O", false, true)
            .SetDateTime("nullableDateTime", source.NullableDateTime, format: "O", false, true)
            .SetDateTimeOffset("dateTimeOffset", source.DateTimeOffset, format: "O", false, true)
            .SetDateTimeOffset("nullableDateTimeOffset", source.NullableDateTimeOffset, format: "O", false, true)
            .SetDecimal("decimal", source.Decimal, false, true)
            .SetDecimal("nullableDecimal", source.NullableDecimal, false, true)
            .SetDouble("double", source.Double, false, true)
            .SetDouble("nullableDouble", source.NullableDouble, false, true)
            .SetGuid("guid", source.Guid, false, true)
            .SetGuid("nullableGuid", source.NullableGuid, false, true)
            .SetInt("int", source.Int, false, true)
            .SetInt("nullableInt", source.NullableInt, false, true)
            .SetLong("long", source.Long, false, true)
            .SetLong("nullableLong", source.NullableLong, false, true)
            .SetString("string", source.String, false, true)
            .SetString("nullableString", source.NullableString, false, true)
            .SetTimeSpan("timeSpan", source.TimeSpan, format: "c", false, true)
            .SetTimeSpan("nullableTimeSpan", source.NullableTimeSpan, format: "c", false, true)
            .SetEnum<global::MyNamespace.OrderStatus>("enum", source.Enum, format: "G", false, true)
            .SetEnum<global::MyNamespace.OrderStatus>("nullableEnum", source.NullableEnum, format: "G", false, true);

    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.ExampleEntity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> x)
    {
        var exampleEntity = new global::MyNamespace.ExampleEntity();
        if (x.TryGetBool("bool", out var var0, Requiredness.InferFromNullability)) exampleEntity.Bool = var0!;
        if (x.TryGetNullableBool("nullableBool", out var var1, Requiredness.InferFromNullability)) exampleEntity.NullableBool = var1!;
        if (x.TryGetDateTime("dateTime", out var var2, format: "O", Requiredness.InferFromNullability)) exampleEntity.DateTime = var2!;
        if (x.TryGetNullableDateTime("nullableDateTime", out var var3, format: "O", Requiredness.InferFromNullability)) exampleEntity.NullableDateTime = var3!;
        if (x.TryGetDateTimeOffset("dateTimeOffset", out var var4, format: "O", Requiredness.InferFromNullability)) exampleEntity.DateTimeOffset = var4!;
        if (x.TryGetNullableDateTimeOffset("nullableDateTimeOffset", out var var5, format: "O", Requiredness.InferFromNullability)) exampleEntity.NullableDateTimeOffset = var5!;
        if (x.TryGetDecimal("decimal", out var var6, Requiredness.InferFromNullability)) exampleEntity.Decimal = var6!;
        if (x.TryGetNullableDecimal("nullableDecimal", out var var7, Requiredness.InferFromNullability)) exampleEntity.NullableDecimal = var7!;
        if (x.TryGetDouble("double", out var var8, Requiredness.InferFromNullability)) exampleEntity.Double = var8!;
        if (x.TryGetNullableDouble("nullableDouble", out var var9, Requiredness.InferFromNullability)) exampleEntity.NullableDouble = var9!;
        if (x.TryGetGuid("guid", out var var10, Requiredness.InferFromNullability)) exampleEntity.Guid = var10!;
        if (x.TryGetNullableGuid("nullableGuid", out var var11, Requiredness.InferFromNullability)) exampleEntity.NullableGuid = var11!;
        if (x.TryGetInt("int", out var var12, Requiredness.InferFromNullability)) exampleEntity.Int = var12!;
        if (x.TryGetNullableInt("nullableInt", out var var13, Requiredness.InferFromNullability)) exampleEntity.NullableInt = var13!;
        if (x.TryGetLong("long", out var var14, Requiredness.InferFromNullability)) exampleEntity.Long = var14!;
        if (x.TryGetNullableLong("nullableLong", out var var15, Requiredness.InferFromNullability)) exampleEntity.NullableLong = var15!;
        if (x.TryGetString("string", out var var16, Requiredness.InferFromNullability)) exampleEntity.String = var16!;
        if (x.TryGetNullableString("nullableString", out var var17, Requiredness.InferFromNullability)) exampleEntity.NullableString = var17!;
        if (x.TryGetTimeSpan("timeSpan", out var var18, format: "c", Requiredness.InferFromNullability)) exampleEntity.TimeSpan = var18!;
        if (x.TryGetNullableTimeSpan("nullableTimeSpan", out var var19, format: "c", Requiredness.InferFromNullability)) exampleEntity.NullableTimeSpan = var19!;
        if (x.TryGetEnum<global::MyNamespace.OrderStatus>("enum", out var var20, global::MyNamespace.OrderStatus.Pending, format: "G", Requiredness.InferFromNullability)) exampleEntity.Enum = var20!;
        if (x.TryGetNullableEnum<global::MyNamespace.OrderStatus>("nullableEnum", format: "G", out var var21, Requiredness.InferFromNullability)) exampleEntity.NullableEnum = var21!;
        return exampleEntity;
    }
}
