//HintName: ExampleEntityMapper.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using DynamoMapper.Runtime;
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;

namespace MyNamespace;

public static partial class ExampleEntityMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> ToItem(global::MyNamespace.ExampleEntity source)
        => new Dictionary<string, AttributeValue>(22)
        {
            { "bool", source.Bool.ToAttributeValue() },
            { "nullableBool", source.NullableBool.ToNullableAttributeValue() },
            { "dateTime", source.DateTime.ToAttributeValue("O") },
            { "nullableDateTime", source.NullableDateTime.ToNullableAttributeValue("O") },
            { "dateTimeOffset", source.DateTimeOffset.ToAttributeValue("O") },
            { "nullableDateTimeOffset", source.NullableDateTimeOffset.ToNullableAttributeValue("O") },
            { "decimal", source.Decimal.ToAttributeValue() },
            { "nullableDecimal", source.NullableDecimal.ToNullableAttributeValue() },
            { "double", source.Double.ToAttributeValue() },
            { "nullableDouble", source.NullableDouble.ToNullableAttributeValue() },
            { "guid", source.Guid.ToAttributeValue() },
            { "nullableGuid", source.NullableGuid.ToNullableAttributeValue() },
            { "int", source.Int.ToAttributeValue() },
            { "nullableInt", source.NullableInt.ToNullableAttributeValue() },
            { "long", source.Long.ToAttributeValue() },
            { "nullableLong", source.NullableLong.ToNullableAttributeValue() },
            { "string", source.String.ToAttributeValue() },
            { "nullableString", source.NullableString.ToNullableAttributeValue() },
            { "timeSpan", source.TimeSpan.ToAttributeValue() },
            { "nullableTimeSpan", source.NullableTimeSpan.ToNullableAttributeValue() },
            { "enum", source.Enum.ToAttributeValue() },
            { "nullableEnum", source.NullableEnum.ToNullableAttributeValue() },
        };
    
    [global::System.CodeDom.Compiler.GeneratedCode("DynamoMapper", "REPLACED")]
    public static partial global::MyNamespace.ExampleEntity FromItem(global::System.Collections.Generic.Dictionary<string, global::Amazon.DynamoDBv2.Model.AttributeValue> item)
        => new global::MyNamespace.ExampleEntity
        {
            Bool = item.GetBool("bool"),
            NullableBool = item.GetNullableBool("nullableBool"),
            DateTime = item.GetDateTimeExact("dateTime", "O"),
            NullableDateTime = item.GetNullableDateTimeExact("nullableDateTime", "O"),
            DateTimeOffset = item.GetDateTimeOffsetExact("dateTimeOffset", "O"),
            NullableDateTimeOffset = item.GetNullableDateTimeOffsetExact("nullableDateTimeOffset", "O"),
            Decimal = item.GetDecimal("decimal"),
            NullableDecimal = item.GetNullableDecimal("nullableDecimal"),
            Double = item.GetDouble("double"),
            NullableDouble = item.GetNullableDouble("nullableDouble"),
            Guid = item.GetGuid("guid"),
            NullableGuid = item.GetNullableGuid("nullableGuid"),
            Int = item.GetInt("int"),
            NullableInt = item.GetNullableInt("nullableInt"),
            Long = item.GetLong("long"),
            NullableLong = item.GetNullableLong("nullableLong"),
            String = item.GetString("string"),
            NullableString = item.GetNullableString("nullableString"),
            TimeSpan = item.GetTimeSpan("timeSpan"),
            NullableTimeSpan = item.GetNullableTimeSpan("nullableTimeSpan"),
            Enum = item.GetEnum("enum", global::MyNamespace.OrderStatus.Pending),
            NullableEnum = item.GetNullableEnum<global::MyNamespace.OrderStatus>("nullableEnum"),
        };
}
